config.code=23
config.menssage=hola que tal como estás? que es ese ñandu?
config.listOfValue= hola que tal que tal tu dia, hoy dia
config.username=ivan2
config.valuesMap={product: "Cpu Intel Core 12th", description: "Alfer Lake, 12 core a 5Ghz", price: "1000"}